# Generated by Django 5.0.6 on 2024-07-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_bestsellingproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestsellingproduct',
            name='slug',
        ),
    ]
