# Generated by Django 5.0.6 on 2024-07-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_bestsellingproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsellingproduct',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
