# Generated by Django 5.0.6 on 2024-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bestsellingproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
