# Generated by Django 5.0.6 on 2024-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_bestsellingproduct_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSellingProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestSelling',
            field=models.BooleanField(default=False),
        ),
    ]
