# Generated by Django 5.0.6 on 2024-07-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_bestsellingproduct_product_is_bestselling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bestSelling',
        ),
        migrations.CreateModel(
            name='BestSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_bestSelling', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='product_images')),
                ('description', models.TextField(blank=True, default='N/A', null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_selling', to='product.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
