# Generated by Django 5.0.6 on 2024-07-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='blog',
            new_name='product',
        ),
    ]
