# Generated by Django 5.0.6 on 2024-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_blog_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestSelling',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BestSellingProduct',
        ),
    ]
