# Generated by Django 5.0.6 on 2024-08-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_is_bestselling_delete_bestsellingproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='image1_title',
            new_name='image_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image2_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image3_title',
        ),
    ]
